app = "tesla-vehicle-command"

primary_region = "ams"

kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  TESLA_HTTP_PROXY_HOST = "0.0.0.0"
  TESLA_HTTP_PROXY_PORT = "8443"

# ---- HTTP/TLS Service ----
[[services]]
  internal_port = 8443        # <-- Porta interna del container
  protocol = "tcp"

  [[services.ports]]
    port = 443                # <-- Porta pubblica
    handlers = ["tls"]        # TLS terminato da Fly

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
