app = "tesla-vehicle-command"
primary_region = "ams"

[build]

[http_service]
  internal_port = 443
  force_https = false      # Perch√© stai usando il tuo certificato TLS, non quello di Fly
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls"]

[checks]
  [checks.proxy]
    type = "tcp"
    port = 443
    interval = "15s"
    timeout = "2s"

[env]
  CONFIG_PATH = "/app/config"
